repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/google/pyink
    rev: 23.3.1
    hooks:
      - id: pyink
        language_version: python3.8
        args: [
          "--line-length=80",
          "--preview",
          "--pyink-indentation=2",
          "--pyink-use-majority-quotes"
        ]
